#指定端口
server:
  port: 8090

spring:
  #数据库
  datasource:
    url: jdbc:mysql://localhost:3306/leanshi
    username: root
    password: leanshi
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${upload.path}

upload:
    path: ${user.dir}/upload

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.leanshi.model

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  level:
    cn:
      leanshi=debug